name: SasaEnhancedProgression
version: '0.1'
main: sasa.progression.sasaEnhancedProgression.SasaEnhancedProgression
api-version: '1.21'
author: SasaSuppenknecht
bootstrapper: sasa.progression.sasaEnhancedProgression.DatapackSetup