name: SasaEnhancedProgression
version: '0.1'
main: sasa.progression.sasaEnhancedProgression.SasaEnhancedProgression
api-version: '1.21'
authors: [SasaSuppenknecht, Maila05]
bootstrapper: sasa.progression.sasaEnhancedProgression.misc.DatapackSetup